# Site 
title: Lei Hua' GitHub Hexo Blog
subtitle: Drafting in Bandwidth, Flighting on Cloud
description: This is my GitHub hexo blog
 
# Pagination 
pagination_dir: pagina
 
# Date / time format 
post_date_format: D [de] MMMM [del] YYYY
 
# Directory 
archive_dir: archivo
category_dir: categoria